-- ACTUAL SEQUELIZE-GENERATED SQL STATEMENTS
-- These are the exact SQL commands that were executed by Sequelize

-- 1. CREATE TABLE statement (generated by Sequelize)
CREATE TABLE IF NOT EXISTS "books" (
    "book_id" SERIAL,
    "title" VARCHAR(255) NOT NULL,
    "author" VARCHAR(255) NOT NULL,
    "borrowed" BOOLEAN DEFAULT false,
    "user_id" INTEGER,
    PRIMARY KEY ("book_id")
);

-- 2. BULK INSERT statement (generated by Sequelize)
INSERT INTO "books" ("book_id","title","author","borrowed","user_id") VALUES 
(DEFAULT,'The Great Gatsby','F. Scott Fitzgerald',false,NULL),
(DEFAULT,'To Kill a Mockingbird','Harper Lee',false,NULL),
(DEFAULT,'1984','George Orwell',true,1),
(DEFAULT,'Pride and Prejudice','Jane Austen',false,NULL),
(DEFAULT,'The Catcher in the Rye','J.D. Salinger',false,NULL),
(DEFAULT,'Harry Potter and the Philosopher''s Stone','J.K. Rowling',true,2),
(DEFAULT,'The Lord of the Rings','J.R.R. Tolkien',false,NULL),
(DEFAULT,'The Hobbit','J.R.R. Tolkien',false,NULL),
(DEFAULT,'Fahrenheit 451','Ray Bradbury',true,3),
(DEFAULT,'The Chronicles of Narnia','C.S. Lewis',false,NULL) 
RETURNING "book_id","title","author","borrowed","user_id";

-- 3. SELECT statement to verify data
SELECT "book_id", "title", "author", "borrowed", "user_id" FROM "books" AS "book";

/*
RESULTS AFTER INSERT:
===================
| book_id | title                                      | author              | borrowed | user_id |
|---------|--------------------------------------------|--------------------|----------|---------|
| 1       | The Great Gatsby                           | F. Scott Fitzgerald | false    | NULL    |
| 2       | To Kill a Mockingbird                      | Harper Lee          | false    | NULL    |
| 3       | 1984                                       | George Orwell       | true     | 1       |
| 4       | Pride and Prejudice                        | Jane Austen         | false    | NULL    |
| 5       | The Catcher in the Rye                     | J.D. Salinger       | false    | NULL    |
| 6       | Harry Potter and the Philosopher's Stone  | J.K. Rowling        | true     | 2       |
| 7       | The Lord of the Rings                      | J.R.R. Tolkien      | false    | NULL    |
| 8       | The Hobbit                                 | J.R.R. Tolkien      | false    | NULL    |
| 9       | Fahrenheit 451                             | Ray Bradbury        | true     | 3       |
| 10      | The Chronicles of Narnia                   | C.S. Lewis          | false    | NULL    |

SUMMARY:
- Total Books: 10
- Available Books: 7 (borrowed = false)
- Borrowed Books: 3 (borrowed = true)
*/